### ISSUE TITLE
Stock "dock" button appears after using DS9FX dock option

### ISSUE THREAD

**Issue by newhalo123** [bcssov/DS9FX#1]
To recreate the bug, first you have to dock to 375 using the ds9fx button. Then, right after leaving the dock, the button to dock using the stock button should appear. If you click on the stock button, your ship will start moving towards the dock point. Then, you will hear an explosion as the docking cutscene happens, and the screen will stay black after the cutscene ends. A game restart is then required.

I've only tested this with the DS9FX defiant. I don't know if it happens with other ships.

I have no additional mods besides the dependencies. (BC 1.1 patch,
Foundation (full install with FTech and Submenu mod),
Unified Main Menu,
and NanoFX 2)

**Comment by mhb210** [comment]
Nero here.  Confirmed.  Only happens at Starbase 375; I checked DS9 and it's not an issue there.

**Comment by bcssov** [comment]
It should be a simple fix to disable programmatically once I get around to this.

**Comment by newhalo123** [comment]
Either the updater didn't update correctly, or the fix didn't fix the issue. I was still able to use the stock dock button

**Comment by mhb210** [comment]
I don't seem to have been able to update properly.  I'll try again.
