### ISSUE TITLE
Suggestion: Restart Campaign Feature

### ISSUE THREAD

**Issue by FekLeyrTarg** [bcssov/DS9FX#10]
When a player finishes a campaign, he/she might want to play it again using a different ship.
A "Restart Campaign" feature could make that possible by locking all campaign mission except the first one and letting the player choose a different ship than last time.

**Comment by bcssov** [comment]
That's already supported, if memory serves me correctly. If you play the 1st mission in a campaign and successfully complete it the following save data progress is saved:
1. Mission progress is inherited from an older save
2. New ship type is saved.

That's pretty close to what you're suggesting. I am closing this issue.

**Comment by FekLeyrTarg** [comment]
Ah ok. I must've missed it somehow.
