### ISSUE TITLE
Not sure how to upload

### ISSUE THREAD

**Issue by mhb210** [bcssov/DS9FX#2]
I'm 100% new to GitHub so I'll probably be asking lots of questions as they come up.  First thing I'm trying to figure out is how I can add some updated hardpoints and plugins to the repository - I've got a few additional hardpoints that weren't included in the 08142017 build and updated a couple others.  I tried the big button that says "upload" but it says I need something called "push access"?

**Comment by bcssov** [comment]
There is no upload as you're used to it here.

1. Download a git client (sourcetree or smartgit for example)
2. Checkout this repository
3. Switch to developer branch
4. Stage new files
5. Commit the changes
6. Push the changes

Also, be sure that you accept my invitation here on github to collaborate on this repository. Finally, master repository is protected I can only push to it. I'd suggest that these questions be posted over at forums :)
