### ISSUE TITLE
Might need some script detection for this

### ISSUE THREAD

**Issue by mhb210** [bcssov/DS9FX#3]
I recently was screwing around with my own custom install - specifically making it so I could dock with the starbases I added to Earth and Mars.  To accomplish this, I copied over the following docking scripts from KM.

The first, located in the "scripts/Custom/QBAutostart" folder is called "CheckDockButton.py", and the second is located in the "scripts/AI/Compound" folder and is called "DockWithStarbaseLong.py".  These two little scripts basically tell BC when you're in a system that has a starbase with a docking hardpoint, and it lights up the stock "Dock" button so you can dock with said starbase.  Works fine, but it also lights up the stock "Dock" button in both our Deep Space 9 system and our Starbase 375 system.

We could put a note in the updated manual to avoid the stock dock button if you're running KM or have these scripts installed, but in the interest of idiot-proofing, I was wondering if it was possible to have DS9FX detect these scripts and overwrite them for DS9FX systems, so that way there's no chance of hitting the stock "Dock" button and causing an error?

**Comment by bcssov** [comment]
I don't want to detect particular scripts, I want to generalize this so I'll be implementing a permanent solution to this for DS9FX systems.

**Comment by mhb210** [comment]
Sounds good :)

**Comment by bcssov** [comment]
I pushed this functionality, can you test and verify it works?

**Comment by bcssov** [comment]
Closing the issue as it appears the solution is universal.
