### ISSUE TITLE
Installing/updating DS9FX overwrites KM's mainmenu.py

### ISSUE THREAD

**Issue by FekLeyrTarg** [bcssov/DS9FX#4]
Installing or updating DS9FX seems to overwrite mainmenu.py. On "Kobayashi Maru"-based installations, this basically removes any KM-specific features of mainmenu.py.

Recommended (temporary) solutions:
#1: If DS9FX's mainmenu.py doesn't contain any needed new features, you can make a manual backup of the KM-one to restore it after installing/updating DS9FX.

#2 If DS9FX's mainmenu.py does contain any needed new features, I'd recommend to put them in KM's one as well and include it in the updater as mainmenu.py.km, so that the KM-player can rename it back to mainmenu.py.

**Comment by mzilic** [comment]
DS9FX supplies vanilla UMM mainmenu.py. However, this is not a DS9FX issue as the release version will, as 1.0, have this as an optional component embedded in the installer. Can you open this very same issue but on the DS9FX updater repository as a reminder? As this particular issue needs to be handled in there.

**Comment by bcssov** [comment]
DS9FX supplies vanilla UMM mainmenu.py. However, this is not a DS9FX issue as the release version will, as 1.0, have this as an optional component embedded in the installer. Can you open this very same issue but on the DS9FX updater repository as a reminder? As this particular issue needs to be handled in there.

**Comment by FekLeyrTarg** [comment]
Done:
https://github.com/bcssov/DS9FX_Updater/issues/1

**Comment by bcssov** [comment]
Closing this one then.
