### ISSUE TITLE
Colonel Kira: Face texture partially misaligned

### ISSUE THREAD

**Issue by FekLeyrTarg** [bcssov/DS9FX#5]
When Colonel Kira welcomes you to DS9, you can see a minor misalignmend of the face texture on her lips.
![kira_misaligned_tex](https://user-images.githubusercontent.com/32707608/31856890-435a92ca-b6ce-11e7-8c98-025e0059806e.jpg)

**Comment by mhb210** [comment]
Mine is the same way.  I assume it's purely model/texture related which is above my pay grade.

**Comment by FekLeyrTarg** [comment]
Issue still exists.

**Comment by bcssov** [comment]
Gonna keep the issue live and wait for BR to review it.

**Comment by bcssov** [comment]
Check the forum thread please. We need more data.

**Comment by FekLeyrTarg** [comment]
1024x768
![screenshot007](https://user-images.githubusercontent.com/32707608/43369800-50705e44-9374-11e8-8fe3-698ae190ebb9.jpg)

**Comment by bcssov** [comment]
It's an issue with the model. Due to lack of tools and people who can fix this I've reverted to the Kira model and textures used in v1.0. Issue closed.
