### ISSUE TITLE
Suggestion: Option to disable local forces during missions

### ISSUE THREAD

**Issue by FekLeyrTarg** [bcssov/DS9FX#6]
During my latest tests, I found it a little disturbing to combat local forces next to the mission generated hostiles during missions. With so many maps, it is quite... complicated to disable local forces for each one.
An option to disable all local forces during missions would make things easier.

**Comment by bcssov** [comment]
Added option, it's off by default. Look under Misc options - other ds9fx options in UMM. Enable and it should remove all ships when a mission is running (10 second timer) and re-add them once the mission is completed. 
Please note that update will overwrite your DS9FX configuration settings.

**Comment by FekLeyrTarg** [comment]
It works, but only at DS9.
In Idran and Kurill, the local forces stay in missions despite the option being enabled.
Also, in the mini-mission "Valiant", this option also removes the Dominion DN.

**Comment by bcssov** [comment]
I believe I missed a spot to add the check for the new option, it's been 10 years. Could be that it breaks more missions, once an update is pushed I'll be counting on you to test :)

**Comment by bcssov** [comment]
I made some changes, haven't tested them please check.

**Comment by FekLeyrTarg** [comment]
Works well in "The Tides of Idran" and "True Way #1".
The DN still gets removed in "Valiant".

**Comment by bcssov** [comment]
Will need to test this mission myself and add print statements to isolate the problem.

**Comment by bcssov** [comment]
Stupid typo, is fixed in the latest commit. Closing.
