### ISSUE TITLE
Bug: Mission Select Screen behind Shield Box in External View

### ISSUE THREAD

**Issue by FekLeyrTarg** [bcssov/DS9FX#8]
When attempting to select a mission on DS9 while in external view, the mission list is stuck behind the shields and weapons box, hindering usability.
The current workaround would be to do so in bridge view.
![mission select external](https://user-images.githubusercontent.com/32707608/42937373-220aae42-8b4f-11e8-854c-7d6c3e50aa59.jpg)

**Comment by bcssov** [comment]
That's a really low resolution you got there.

**Comment by FekLeyrTarg** [comment]
I've set it to 1024x768, the second highest official resolution, because 1280x1024 causes some major cropping for some reason. Haven't tried the custom ones yet.

**Comment by bcssov** [comment]
I did something (moved the menu on lower resolutions to the left), pull via updater and let me know the results.

**Comment by FekLeyrTarg** [comment]
Yes, this has improved it a bit.
Could it perhabs moved up a little?
(I haven't tested it on 800x600 and 640x480 yet.)

![mission select external 2](https://user-images.githubusercontent.com/32707608/43162597-d2ad1bdc-8f8b-11e8-908a-ec844eb6fde7.jpg)

**Comment by bcssov** [comment]
Ok, don't know how it will look on even lower resolutions. Will need to check.

**Comment by bcssov** [comment]
Made some adjustments, adjusting for resolutions like 800x600 or 640x480 is a pain in the ass and won't be supporting these that much. Let me know how the latest changes are and we can close the issue.

**Comment by FekLeyrTarg** [comment]
Much better. Thank you very much.
I think 800x600 and 640x480 won't be necessary as I doubt anyone would play BC in these resolutions nowadays.

**Comment by bcssov** [comment]
Closing the issue then.

**Comment by bcssov** [comment]
Added logic to detect custom resolutions as well.
